### ISSUE TITLE
The evaluation of F-score and Chamfer Distance (CD) 

### ISSUE THREAD

**Issue by Liuzhengli** [DaLi-Jack/SSR-code#16]
The evaluation of F-score and Chamfer Distance (CD) metrics is suddenly encountering errors for the last hundred items.
Hello author, I have evaluated on your pre-trained model, and the NC metric matches the original numbers, but when evaluating the F-score and Chamfer Distance (CD) metrics, everything was normal until the last hundred items suddenly had errors. Could you please provide an explanation
![1111](https://github.com/user-attachments/assets/a52babd7-6f9f-4317-82f4-ebfbdd8aba5a)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/environment/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/environment/miniconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/environment/miniconda3/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/environment/miniconda3/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/featurize/work/SSR-code-main/eval/evaluate_front3d.py", line 166, in run_in_one
    gt_mesh.vertices=gt_mesh.vertices/2*size/np.max(size)*2
AttributeError: 'Scene' object has no attribute 'vertices'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "eval/evaluate_front3d.py", line 239, in <module>
    Parallel()(delayed(evaluate.run_in_one)(index) for index in range(len(evaluate.split)))
  File "/environment/miniconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/environment/miniconda3/lib/python3.7/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/environment/miniconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AttributeError: 'Scene' object has no attribute 'vertices'

**Comment by DaLi-Jack** [comment]
It seems like this issue stems from loading the mesh using Trimesh. I haven’t encountered this problem before, but I believe you can modify [this code](https://github.com/DaLi-Jack/SSR-code/blob/d40bd0226ae6f9169a37efd8a84a7a0a50467997/eval/evaluate_front3d.py#L162) : 
`pred_mesh = trimesh.load(pred_cube_mesh_path)`
`gt_mesh = trimesh.load(gt_cube_mesh_path)`
to : 
`pred_mesh = trimesh.load(pred_cube_mesh_path, force='mesh')`
`gt_mesh = trimesh.load(gt_cube_mesh_path, force='mesh')`
This should help avoid the issue. You can refer to [the official Trimesh answer here](https://github.com/mikedh/trimesh/issues/1585).

**Comment by Liuzhengli** [comment]
Hello, I tested it again and the issue persists. Could there possibly be a problem with the code?，And it always stops at 2678.

**Comment by DaLi-Jack** [comment]
Perhaps you can try the following code:
![image](https://github.com/user-attachments/assets/25c09d90-e739-48e1-951d-4e58309658db)
As mentioned previously, the problem was that 'trimesh.Scene' cannot use the attribute 'vertices'. The code in the figure can convert 'trimesh.Scene' to 'trimesh.Trimesh', and then 'vertices' can be used. Although I originally thought that the previous answer could solve the problem.

**Comment by Rakesh-Paul01** [comment]
Hey @DaLi-Jack regarding an error which occurred with me on when running `bash eval/evaluate.sh configs/train_pix3d.yaml` is that I'm getting 

```
./output/pix3d_exp/out/desk/0137_255/pred_cube.ply
./output/pix3d_exp/out/table/0773_255/pred_cube.ply
./output/pix3d_exp/out/sofa/0357_255/pred_cube.ply
./output/pix3d_exp/out/table/1340_255/pred_cube.ply
./output/pix3d_exp/out/table/0740_255/pred_cube.ply
./output/pix3d_exp/out/chair/0304_255/pred_cube.ply
./output/pix3d_exp/out/desk/0399_255/pred_cube.ply
./output/pix3d_exp/out/chair/1706_255/pred_cube.ply
./output/pix3d_exp/out/chair/1418_255/pred_cube.ply
./output/pix3d_exp/out/bookcase/0130_255/pred_cube.ply
./output/pix3d_exp/out/table/0027_255/pred_cube.ply
./output/pix3d_exp/out/table/0040_255/pred_cube.ply
Traceback (most recent call last):
  File "evaluate_front3d.py", line 242, in <module>
    evaluate.run()
  File "evaluate_front3d.py", line 202, in run
    self.get_result()
  File "evaluate_front3d.py", line 102, in get_result
    mean_f_score = total_score/total_number
ZeroDivisionError: division by zero

```

checking the file, I found out that the `total_number` was not being updated in line [98](https://github.com/DaLi-Jack/SSR-code/blob/d40bd0226ae6f9169a37efd8a84a7a0a50467997/eval/evaluate_front3d.py#L98)

looking more into it found that the `self.cd_loss_dict` is actually empty. Can you suggest how to fix this issue and what step are to be followed. 

Also note: I have changed the path of `eval/evaluate_front3d.py` to `evaluate_front3d.py` also I have moved the file there. This is done since `from external.pyTorchChamferDistance.chamfer_distance import ChamferDistance
i` was throwing an error of can't import ChamferDistance, but from the global directory it was able to import the ChamferDistance. 


Edit:

digging a bit more deeper I found out that the following paths are not present with me. This block of code is from [here](https://github.com/DaLi-Jack/SSR-code/blob/d40bd0226ae6f9169a37efd8a84a7a0a50467997/eval/evaluate_front3d.py#L139)

```python
        output_folder = os.path.join(self.cfg['result_dir'], classname, f'{str(img_id)}_{str(obj_id)}')
        pred_cube_mesh_path = os.path.join(output_folder, 'pred_cube.ply')
        gt_cube_mesh_path = os.path.join(output_folder, 'label_cube.ply')
```
checking the self.loginfo also gives me the following:
```
/bookcase/0130_255/pred_cube.ply is not exist!', 'pred: ./output/pix3d_exp/out/table/0027_255/pred_cube.ply is not exist!', 'pred: ./output/pix3d_exp/out/table/0040_255/pred_cube.ply is not exist!']

```

Instead I have the following:
```
object_resize
mesh_color.ply
mesh_none_color.ply
```

Also note that object_resize directory is empty.

**Comment by DaLi-Jack** [comment]
> Hey [@DaLi-Jack](https://github.com/DaLi-Jack) regarding an error which occurred with me on when running `bash eval/evaluate.sh configs/train_pix3d.yaml` is that I'm getting
> 
> ```
> ./output/pix3d_exp/out/desk/0137_255/pred_cube.ply
> ./output/pix3d_exp/out/table/0773_255/pred_cube.ply
> ./output/pix3d_exp/out/sofa/0357_255/pred_cube.ply
> ./output/pix3d_exp/out/table/1340_255/pred_cube.ply
> ./output/pix3d_exp/out/table/0740_255/pred_cube.ply
> ./output/pix3d_exp/out/chair/0304_255/pred_cube.ply
> ./output/pix3d_exp/out/desk/0399_255/pred_cube.ply
> ./output/pix3d_exp/out/chair/1706_255/pred_cube.ply
> ./output/pix3d_exp/out/chair/1418_255/pred_cube.ply
> ./output/pix3d_exp/out/bookcase/0130_255/pred_cube.ply
> ./output/pix3d_exp/out/table/0027_255/pred_cube.ply
> ./output/pix3d_exp/out/table/0040_255/pred_cube.ply
> Traceback (most recent call last):
>   File "evaluate_front3d.py", line 242, in <module>
>     evaluate.run()
>   File "evaluate_front3d.py", line 202, in run
>     self.get_result()
>   File "evaluate_front3d.py", line 102, in get_result
>     mean_f_score = total_score/total_number
> ZeroDivisionError: division by zero
> ```
> 
> checking the file, I found out that the `total_number` was not being updated in line [98](https://github.com/DaLi-Jack/SSR-code/blob/d40bd0226ae6f9169a37efd8a84a7a0a50467997/eval/evaluate_front3d.py#L98)
> 
> looking more into it found that the `self.cd_loss_dict` is actually empty. Can you suggest how to fix this issue and what step are to be followed.
> 
> Also note: I have changed the path of `eval/evaluate_front3d.py` to `evaluate_front3d.py` also I have moved the file there. This is done since `from external.pyTorchChamferDistance.chamfer_distance import ChamferDistance i` was throwing an error of can't import ChamferDistance, but from the global directory it was able to import the ChamferDistance.
> 
> Edit:
> 
> digging a bit more deeper I found out that the following paths are not present with me. This block of code is from [here](https://github.com/DaLi-Jack/SSR-code/blob/d40bd0226ae6f9169a37efd8a84a7a0a50467997/eval/evaluate_front3d.py#L139)
> 
>         output_folder = os.path.join(self.cfg['result_dir'], classname, f'{str(img_id)}_{str(obj_id)}')
>         pred_cube_mesh_path = os.path.join(output_folder, 'pred_cube.ply')
>         gt_cube_mesh_path = os.path.join(output_folder, 'label_cube.ply')
> checking the self.loginfo also gives me the following:
> 
> ```
> /bookcase/0130_255/pred_cube.ply is not exist!', 'pred: ./output/pix3d_exp/out/table/0027_255/pred_cube.ply is not exist!', 'pred: ./output/pix3d_exp/out/table/0040_255/pred_cube.ply is not exist!']
> ```
> 
> Instead I have the following:
> 
> ```
> object_resize
> mesh_color.ply
> mesh_none_color.ply
> ```
> 
> Also note that object_resize directory is empty.

It looks like your issue is related to an error in indexing the path where the results are saved. You might want to double-check it. I ran the code directly and didn’t encounter any problems.
